### ISSUE TITLE
File List Improvements

### ISSUE THREAD

**Issue by flauc** [Jaspero/web-components#127]
- [x] Selecting the same item twice doesn't work. This is a very common bug and it happens because the file input field retains the first selection and doesn't trigger a change event. 
- [x] We need to add the option to sort the list by dragging files around
- [x] The label attribute isn't supported, this is just to allow for consistency between form fields. Please see if any other attributes might be sensible to include as well. 
   ![image](https://github.com/Jaspero/web-components/assets/4489834/da5fe795-ff84-474d-a42d-a999d82c9bcb)
- [x] The style is slightly different from a typical field: we don't have border radius and the width is slightly bigger. 
- [x] It also looks like the width of the field isn't properly constrained by its parent
  ![image](https://github.com/Jaspero/web-components/assets/4489834/1dd3ce20-3a3d-4f5d-b609-e55a4a5e8556)

**Comment by KovaCro** [comment]
- [ ] Fix flickering when dragging file over center of field

**Comment by flauc** [comment]
@Ktarnaj can you pick up the style adjustments needed for those last few points please?

**Comment by Ktarnaj** [comment]
closed with commit [20e6fb9](https://github.com/Jaspero/web-components/commit/20e6fb9f1ea4c9ac3077aed0155ebd3b109edb1c)
