### ISSUE TITLE
File list style

### ISSUE THREAD

**Issue by KovaCro** [Jaspero/web-components#136]
The file list isn't properly styled for widths smaller than 600px and its max width is 750px. Its height is also fixed. 

![image](https://github.com/Jaspero/web-components/assets/21172768/4b6c4ec3-07b5-4b07-8795-d28ed1cad35c)

Also, when items are dragged content overflows:

![image](https://github.com/Jaspero/web-components/assets/21172768/de212e57-ecc2-4053-b8ed-1f6865a626bb)

The file list should adapt to the parent size and be responsive.

**Comment by Ktarnaj** [comment]
closed with https://github.com/Jaspero/web-components/commit/2a94d306e0726fc0a0228d38e0975ba9a10e1209
