### ISSUE TITLE
Textarea field formatting issue

### ISSUE THREAD

**Issue by bridget75** [Jaspero/web-components#153]
![image](https://github.com/Jaspero/web-components/assets/93909566/5313a391-dbc6-47bf-8d6e-36b2cda06875)

 - make this field dinamic, if you write more more characters than it is possible to show, spread this field
- currenlty is will go in one line only and without scroll bar it is not visible at all, but spread it down when there is too much content typed

**Comment by Ktarnaj** [comment]
Closed with Commit [c7d73fd](https://github.com/Jaspero/web-components/commit/c7d73fdc946fc603b99e1a038601392989238015)
