### ISSUE TITLE
ckeditor - Error on focus

### ISSUE THREAD

**Issue by makiJS** [Jaspero/web-components#251]
![image](https://github.com/user-attachments/assets/65143b1c-5eb6-48c2-b528-45a27cb9ca32)
![image](https://github.com/user-attachments/assets/d4fe28d1-7536-4a34-ad45-5014b52094f8)

**Comment by AnteSuvala** [comment]
![Screenshot (17)](https://github.com/user-attachments/assets/df230ca7-b8d1-49ca-9c9e-fdabd29e422c)
can't recreate error
