### ISSUE TITLE
Create Select Field

### ISSUE THREAD

**Issue by flauc** [Jaspero/web-components#5]
Another field we need to create. It should accept an array of label/value objects and all of the common properties of a select (check the input field I added for reference).

**Comment by flauc** [comment]
@KovaCro one thing I'm noticing on this one. It should be possible to assign a different name and value to the options. In other words the options should be an array of `{name: string; value: string}` not a string array.

**Comment by Ktarnaj** [comment]
select should open an overlay and display the menu there because if somebody puts a select element inside a block with overflow: hidden; the menu will definitely get cut off.

same thing with #6 

i'll be working on this.
