### ISSUE TITLE
Docs: clicking on the select will crash the page

### ISSUE THREAD

**Issue by Ktarnaj** [Jaspero/web-components#72]
When you got to either [select](https://jaspero.github.io/web-components/docs/Form%20fields/select) or [multiselect](https://jaspero.github.io/web-components/docs/Form%20fields/multiselect) and click on the select in the demo, you will notice that the webpage freezes and goes unresponsive. Please investigate this

**Comment by KovaCro** [comment]
Solving #73 will resolve this issue
