### ISSUE TITLE
Image Adjustment

### ISSUE THREAD

**Issue by flauc** [Jaspero/web-components#89]
I realized the image can just as well be used as a file upload since the allowed types can be adjusted. I think we should rename the component to file upload and just make `showPreview` as an option that defaults to true. 

In the demo we can then have examples for both an image upload and a file upload. 

@Ktarnaj it also looks like the preview it self is a bit broken in the demo.

**Comment by KovaCro** [comment]
@flauc I made it without `showPreview` attribute, the preview will be available if link or file selected is an image. If need be we can later add preview for textual files as well.

**Comment by flauc** [comment]
Perfect

**Comment by KovaCro** [comment]
Preview in demo will be resolved with #101
