### ISSUE TITLE
Image gallery component

### ISSUE THREAD

**Issue by KovaCro** [Jaspero/web-components#93]
It should look something like this: https://mui.com/material-ui/react-image-list/#quilted-image-list

**Comment by flauc** [comment]
Here is another great example I was just considering for another project. 

https://photoswipe.com/

It would be awesome to be able to use our component instead. 

![image](https://github.com/Jaspero/web-components/assets/4489834/b0a3b41e-0339-4827-b839-e117d7187ff4)

The masonry option specifically is what I needed.
