### ISSUE TITLE
Datepicker Issues

### ISSUE THREAD

**Issue by flauc** [Jaspero/web-components#98]
![image](https://github.com/Jaspero/web-components/assets/4489834/59cee011-1c9c-43ca-84e7-412766a8ef72)

I'm getting a lot of issues like this. I have it just configured like this:

```js
  {
      component: 'jp-datepicker',
      field: '/createdOn',
      options: {
        label: 'Created on',
        name: 'createdOn'
      }
    }
```

And the value it get's is `Date.now()`. 

Can you investigate a bit please?

**Comment by KovaCro** [comment]
@flauc I don't know how to replicate this error

**Comment by flauc** [comment]
@KovaCro I switched it to me and will investigate further.
